### PR TITLE
Fix to the parameter transformation functionality

### PR DESCRIPTION
**Pull request by yonatank93**
List of changes:
* Set `kliff.model.Models().model_params` as an attribute that store
the parameter values in the original parameterization.
* Move the transformation and inverse transform to
`kliff.model.OptimizingParameters()`, e.g., the transform function in `get_opt_params` and
the inverse transform in `update_opt_params` methods. This also requires the parameter
transfomation class to be passed in to `OptimizingParameters`.
* Add a line in the echo methods saying that the printed values are in
the original parameterization.

### CODE REVIEW

**Comment by mjwen** [comment]
@yonatank93 thank for the PR! Can you please enable `Allow edits from maintainers` for me to make some adjustment?

**Comment by yonatank93** [comment]
@mjwen I enabled `Allow edits from maintainers`. Let me know if this is not working.

**Comment by mjwen** [comment]
The functionality to deal with parameter transformation has all been moved to the `Model` class, leaving `OptimizingParams` free. Except the below behaviors: 

- `model.echo_opt_params()` will always show the transformed params 

- A new parameter `parameter_space` added `model.echo_model_params(parameter_space=...)`. A value of `original` will show params in the untransformed space (this is the default behavior), and a value of `transformed` will show it in the transformed space.   

@yonatank93 Can you test this out and let me know whether this solves your problem?

**Comment by mjwen** [comment]
Agreed! It's useful to let the user know that it's in the transformed space. Added. 

Also, it would be helpful to add a tutorial example to demonstrate this. Can you convert your Jupyter notebook to an example as those listed [here](https://github.com/openkim/kliff/tree/master/examples)? Probably take a look at  [example_kim_SW_Si.py](https://github.com/openkim/kliff/blob/master/examples/example_kim_SW_Si.py). The docstrings in the examples follow the [sphinx-gallery](https://sphinx-gallery.github.io/stable/syntax.html) syntax.

**Comment by yonatank93** [comment]
Sure, I will do it later today. In the example, we want to show:
* How to use, say, log transformation, which will also include some motivation why we want to transform the parameter space.
* Do we also want to show how to construct different parameter transformation class?
* Update the parameter values in the transformed space.
* Do we want to show the difference in the result when we use the original vs transformed space?

**Comment by mjwen** [comment]
Thanks! 
- We may not want to show how to construct different parameter transformation in this tutorial. But can say that a user can do it easily by subclassing the `ParameterTransform` class. 

- It might be difficult/lengthy to compare the results. So, probably not do it at this stage. We may need longer docs/tutorials once all the UQ stuff is fleshed out. Then, we can do it in a more thorough way. 

I will merge and close this. Feel free to open a new PR for the tutorial.

**Pull request merged**
